[package]
name = "elvwf-derive"
version = "0.1.1"
edition = "2024"
description = "Bit-precise wire format definitions"
repository = "https://hennzau.fr/jj/elvwf"
keywords = ["codec", "binary", "wire", "derive", "protocol"]
categories = ["encoding", "network-programming", "no-std"]

readme = "../README.md"
license = "AGPL-3.0-only"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1" }
quote = { version = "1" }
syn = { version = "2", features = ["full", "visit-mut"] }
darling = { version = "0.23" }
