//! Warning: this file has been mostly generated by Claude.
//! I checked for its correctness and as far as I can tell, it is ok.

use proc_macro2::TokenStream;
use quote::ToTokens;
use syn::{spanned::Spanned, *};

use super::super::utils::strip_lifetimes;

#[derive(Debug)]
pub(crate) enum FieldKind {
    Optional(FieldShape),
    Plain(FieldShape),
}

#[derive(Debug)]
pub(crate) enum FieldShape {
    Scalar((Type, Type)),
    Slice((Type, Type)),
    Msg((Type, Type)),
}

impl ToTokens for FieldShape {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let (Self::Scalar((ty, _)) | Self::Slice((ty, _)) | Self::Msg((ty, _))) = self;
        ty.to_tokens(tokens);
    }
}

impl ToTokens for FieldKind {
    fn to_tokens(&self, tokens: &mut TokenStream) {
        let (Self::Optional(shape) | Self::Plain(shape)) = self;
        shape.to_tokens(tokens);
    }
}

const SCALAR_IDENTS: &[&str] = &[
    "u8", "u16", "u32", "u64", "u128", "usize", "i8", "i16", "i32", "i64", "i128", "isize", "f32",
    "f64",
];

fn is_scalar(ty: &Type) -> bool {
    let Type::Path(TypePath { qself: None, path }) = ty else {
        return false;
    };

    let Some(ident) = path.get_ident() else {
        return false;
    };

    SCALAR_IDENTS.iter().any(|s| ident == s)
}

fn as_option(ty: &Type) -> Option<&Type> {
    let Type::Path(TypePath { qself: None, path }) = ty else {
        return None;
    };
    let seg = path.segments.last()?;
    if seg.ident != "Option" {
        return None;
    }

    let PathArguments::AngleBracketed(args) = &seg.arguments else {
        return None;
    };
    if args.args.len() != 1 {
        return None;
    }
    match args.args.first()? {
        GenericArgument::Type(inner) => Some(inner),
        _ => None,
    }
}

fn is_u8(ty: &Type) -> bool {
    matches!(ty, Type::Path(TypePath { qself: None, path }) if path.is_ident("u8"))
}

fn classify_shape(ty: &Type) -> Result<FieldShape> {
    if is_scalar(ty) {
        return Ok(FieldShape::Scalar((ty.clone(), strip_lifetimes(ty))));
    }

    if let Type::Reference(TypeReference { elem, .. }) = ty {
        match &**elem {
            Type::Path(TypePath { qself: None, path })
                if path.is_ident("str") || path.is_ident("CStr") =>
            {
                return Ok(FieldShape::Slice((ty.clone(), strip_lifetimes(ty))));
            }
            Type::Slice(TypeSlice { elem, .. }) | Type::Array(TypeArray { elem, .. }) => {
                if !is_u8(elem) {
                    return Err(Error::new(
                        elem.span(),
                        "only `&[u8]` or `&[u8; N]` slices are supported",
                    ));
                }
                return Ok(FieldShape::Slice((ty.clone(), strip_lifetimes(ty))));
            }
            _ => {
                return Err(Error::new(
                    ty.span(),
                    "unsupported reference type: expected `&str`, `&CStr`, `&[u8]` or `&[u8; N]`",
                ));
            }
        }
    }

    Ok(FieldShape::Msg((ty.clone(), strip_lifetimes(ty))))
}

pub fn classify(ty: &Type) -> Result<FieldKind> {
    if let Some(inner) = as_option(ty) {
        if as_option(inner).is_some() {
            return Err(Error::new(
                inner.span(),
                "nested `Option<Option<…>>` is not supported",
            ));
        }
        classify_shape(inner).map(FieldKind::Optional)
    } else {
        classify_shape(ty).map(FieldKind::Plain)
    }
}
